<?php
/**
 * Created by PhpStorm.
 * User: apuc0
 * Date: 15.10.2016
 * Time: 16:09
 */

namespace frontend\modules\adsmanager\widgets;


use common\classes\Debug;
use common\models\db\User;
use frontend\assets\ClAssets;
use frontend\models\user\UserDec;
use vision\messages\widgets\CloadMessage;

class Msg extends CloadMessage
{

    public $user_id;

    /*public function run()
    {
        return parent::run(); // TODO: Change the autogenerated stub
    }*/

    protected function getListUsers(){
        //$users = \Yii::$app->mymessages->getAllUsers();
        $user = UserDec::find()->where(['id'=>$this->user_id])->one();
        $users[] = [
            'id' => $user->id,
            'username' => $user->username,
        ];
        $html = '<div class="list_users message-user-list friends-message-layout">';
        $html .= '<div id="scrollbar3">
		 	<div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>
			<div class="viewport">
			<div class="overview">';

        foreach($users as $usr) {
            $username = trim($usr[\Yii::$app->mymessages->attributeNameUser]);
            $names = explode(' ', $username);
            $html .= '<div class="contact friends" data-name="' . $username . '" data-user="' . $usr['id'] . '">';

            $html .= '<button class="delete-friend">&times;</button>';

            $html .= '<span class="counter-message" style="display:' . ($usr['cnt_mess'] > 0 ? 'block' : 'none') . '">';
            if($usr['cnt_mess']){
                $html .=  $usr['cnt_mess'];
            }
            $html .= '</span>';
            $img = \Yii::$app->mymessages->createLogo($usr['id']);
            if($img) {
                $html .= '<div class="friends-block">';
                $html .=  $img;
                $html .= '</div>';
            }

            $html .= '<div class="friends-name">';

            $html .= array_reduce($names, function($pre, $val) {
                return $pre . "<div>$val</div>";
            });
            $html .= "</div></div>";
        }

        $html .= '</div></div></div></div>';
        return $html;
    }


    protected function addJs(){
        $view = $this->getView();
        $var_name = 'mess_' . $this->uniq_id;
        $base = "var baseUrlPrivateMessage ='" . \Yii::$app->mymessages->nameController . "';";
        $view->registerJs($base, $view::POS_BEGIN);
        $script = 'var ' . $var_name . ' = new visiPrivateMessages("#'. $this->uniq_id .'");';
        $script .= "$var_name.getAllMessages();";
        $script .= "$var_name.cau($this->user_id);";
        $script .= "console.log();";
        $view->registerJs($script, $view::POS_READY);
    }

    protected function assetJS(){
        ClAssets::register($this->view);
        $this->addJs();
    }
}