<?php
/**
 * Created by PhpStorm.
 * User: apuc0
 * Date: 21.01.2017
 * Time: 12:08
 */

namespace frontend\widgets;


use yii\base\Widget;

class ShowTree extends Widget
{

    public $parent_field = 'parent_id';
    public $tpl = 'ul';
    public $item = 'li';

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }

}